@{
    'cfg.default'    = 'default'
    'cfg.choice'     = 'Choice 1-{0} [Enter = {1}]'
    'cfg.yn'         = 'Y/n'
    'cfg.ny'         = 'y/N'
    'cfg.yes'        = 'yes'
    'cfg.on'         = 'on'
    'cfg.off'        = 'off'
    'cfg.kept'       = 'kept'
    'cfg.unchanged'  = 'unchanged'
    'cfg.confirm'    = 'Confirm?'
    'cfg.noGrid'     = 'Out-GridView is not available ({0}) - selecting in the console'
    'cfg.numbers'    = 'Numbers separated by commas, ranges 1-5, * = all, Enter = none'

    'cfg.step'       = 'CONFIGURE - image configuration wizard'
    'cfg.notSystem'  = 'Run Configure interactively from the administrator account.'
    'cfg.step1'      = 'Step 1/8: profile'
    'cfg.profile'    = 'Image profile:'
    'cfg.profile.uni'= 'University - labs, students and staff'
    'cfg.profile.bus'= 'Business - office workers, heavy Teams use, data in OneDrive'
    'cfg.profile.gfx'= 'Graphics / designer - vGPU, full visual effects, GPU acceleration in applications'

    'cfg.step2'           = 'Step 2/8: Microsoft 365 Apps (Office Deployment Tool)'
    'cfg.noOffice'        = 'No Office365 entry in the manifest - skipped'
    'cfg.oldXmlBad'       = 'Existing {0}: XML error - it will be replaced'
    'cfg.license'         = 'Microsoft 365 license (Shared Computer Activation works only with these plans):'
    'cfg.license.ent'     = 'Microsoft 365 Apps for enterprise / education (O365ProPlusRetail) - E3/E5, A3/A5'
    'cfg.license.bus'     = 'Microsoft 365 Apps for business (O365BusinessRetail) - Business Premium ONLY'
    'cfg.channel'         = 'Update channel (you update the image yourself in the Update cycle):'
    'cfg.channel.mec'     = 'MonthlyEnterprise - once a month, predictable (recommended for VDI)'
    'cfg.channel.cc'      = 'Current - newest features, more frequent changes'
    'cfg.channel.sac'     = 'SemiAnnual - twice a year, the most stable'
    'cfg.lang'            = 'Main Office language:'
    'cfg.lang.pl'         = 'Polish (pl-pl)'
    'cfg.lang.en'         = 'English (en-us)'
    'cfg.lang.de'         = 'German (de-de)'
    'cfg.lang.fr'         = 'French (fr-fr)'
    'cfg.lang.plen'       = 'Polish + English (pl-pl + en-us, both full)'
    'cfg.lang.other'      = 'other language (enter the code)'
    'cfg.lang.code'       = 'Office language code (e.g. it-it, cs-cz, uk-ua)'
    'cfg.lang2'           = 'Second language:'
    'cfg.lang2.none'      = 'none (one language - smallest image, fastest update)'
    'cfg.lang2.proof'     = 'proofing tools only (ProofingTools) - spelling in the second language'
    'cfg.lang2.full'      = 'full language pack (user interface + spelling)'
    'cfg.lang2.code'      = 'Second language'
    'cfg.app.access'      = 'Microsoft Access'
    'cfg.app.onenote'     = 'OneNote (desktop version)'
    'cfg.app.publisher'   = 'Publisher - Microsoft retires it in October 2026, exclusion recommended'
    'cfg.app.outlook'     = 'Outlook (classic)'
    'cfg.excludedNow'     = 'Excluded now: {0}'
    'cfg.excludeTitle'    = 'Select the applications to EXCLUDE from the image (Ctrl = several)'

    'cfg.stepJava'        = 'Step 3/8: Java development (Temurin JDK + Eclipse IDE)'
    'cfg.java.enable'     = 'Install Java development tools (Temurin JDK + Eclipse IDE)?'
    'cfg.java.off'        = 'Java/Eclipse packages disabled (already installed versions stay in the image, they are just not updated)'
    'cfg.java.jdk'        = 'Which JDKs? (the first one sets JAVA_HOME, PATH and .jar)'
    'cfg.java.jdk.both'   = 'Temurin 21 + 25 LTS (JAVA_HOME = 21)'
    'cfg.java.jdk.21'     = 'Temurin 21 LTS only'
    'cfg.java.jdk.25'     = 'Temurin 25 LTS only'
    'cfg.java.pkg'        = 'Eclipse package'
    'cfg.java.pkg.java'   = 'Eclipse IDE for Java Developers'
    'cfg.java.pkg.jee'    = 'Eclipse IDE for Enterprise Java and Web Developers (ZIP downloaded manually)'
    'cfg.java.forceWs'    = 'Open the workspace in the FSLogix container without asking (recommended for student labs)?'
    'cfg.java.heap'       = 'Maximum IDE memory -Xmx in MB (0 = JVM default, about 1/4 of the VM RAM)'
    'cfg.java.heapBad'    = '{0} is not 0 or 512-32768 - using 0 (JVM default)'
    'cfg.java.caches'     = 'Exclude the Maven/Gradle caches (.m2\repository, .gradle\caches) from the FSLogix container? Only with a nearby Maven mirror - they are downloaded again in every session'
    'cfg.java.noPkg'      = 'Package {0} is neither in the manifest nor in the template - skipped'
    'cfg.java.pkgAdded'   = 'Package {0} added to the manifest from the template'
    'cfg.java.jeeDownload' = '-Mode Download fetches only the java ZIP: put eclipse-jee-<YYYY-MM>-R-win32-x86_64.zip into Apps\Eclipse yourself'
    'cfg.java.done'       = 'Java: JDK {0}, Eclipse {1} | EclipseJava Arguments: {2}'

    'cfg.step3'           = 'Step 4/8: FSLogix (profile containers)'
    'cfg.fsl.share'       = 'Share for profile containers (UNC, e.g. \\fs01\Profiles$; Enter = skip)'
    'cfg.fsl.none'        = 'FSLogix: no share - the configuration stays disabled'
    'cfg.fsl.notUnc'      = 'Not a UNC path: {0} - skipped'
    'cfg.fsl.size'        = 'Maximum VHDX size in MB'
    'cfg.fsl.include'     = 'Groups that get a container, comma separated (Enter = everyone)'
    'cfg.fsl.exclude'     = 'Accounts/groups WITHOUT a container, e.g. DOMAIN\VDI-Admins (Enter = none)'
    'cfg.fsl.noPkg'       = 'No FSLogixConfig entry in the manifest - skipped'
    'cfg.fsl.done'        = 'FSLogixConfig: {0} (enabled)'

    'cfg.step4'           = 'Step 5/8: Horizon Agent and App Volumes'
    'cfg.hz.help'         = 'Horizon Agent features (ADDLOCAL): Core and NGVC (Instant Clone) are required; Core already contains Blast, PCoIP and Media Optimization for Teams. Optional: USB, RTAV (webcam/microphone), ClientDriveRedirection, ScannerRedirection, SmartCard, SerialPortRedirection, GEOREDIR, PerfTracker, HelpDesk, PrintRedir.'
    'cfg.hz.features'     = 'Horizon Agent ADDLOCAL (comma-separated; Enter = suggestion for the profile)'
    'cfg.av.manager'      = 'App Volumes Manager address (FQDN; Enter = unchanged)'
    'cfg.av.port'         = 'App Volumes Manager port'

    'cfg.step5'           = 'Step 6/8: regional settings for the image build (OOBE after Generalize)'
    'cfg.bld.tz'          = 'Time zone (Get-TimeZone -ListAvailable)'
    'cfg.bld.system'      = 'System locale'
    'cfg.bld.user'        = 'User date/number format'
    'cfg.bld.input'       = 'Keyboard'
    'cfg.bld.ui'          = 'User interface language after OOBE = installed Windows language ({0})'

    'cfg.step6'           = 'Step 7/8: OSOT - Teams, OneDrive, visual effects'
    'cfg.osot.none'       = 'No Osot section in the manifest - skipped'
    'cfg.osot.notif'      = 'Keep app notifications (Teams: chat, incoming calls)?'
    'cfg.osot.onedrive'   = 'Users keep their data in OneDrive (Known Folder Move) - keep OneDrive and install it per machine?'
    'cfg.osot.noFile'     = 'OSOT selections file {0} not found - skipped'
    'cfg.osot.odPkg'      = 'OneDrive package (per machine): {0}'
    'cfg.osot.odMissing'  = 'No OneDrive entry in the manifest - add OneDriveSetup.exe to Apps\ (docs/profiles-gpo.md)'
    'cfg.osot.changed'    = 'Optimize.json: {0} items changed (notifications: {1}, OneDrive: {2}, effects: {3})'
    'cfg.osot.same'       = 'Optimize.json: no changes'
    'cfg.osot.verify'     = 'To verify on a clone: "Let Windows apps run in the background" (Optimize.json) must not block Teams in the background'

    'cfg.step7'           = 'Step 8/8: winget applications'
    'cfg.wg.noCatalog'    = 'Catalog {0} not found - application selection skipped'
    'cfg.col.name'        = 'Name'
    'cfg.col.category'    = 'Category'
    'cfg.col.profile'     = 'For profile'
    'cfg.col.suggest'     = 'Suggested'
    'cfg.col.current'     = 'Selected now'
    'cfg.col.block'       = 'Update blocking'
    'cfg.wg.current'      = 'In the manifest now: {0}'
    'cfg.wg.title'        = 'Select the applications to install in the image (Ctrl/Shift = several), then OK'
    'cfg.wg.nothing'      = 'Nothing selected.'
    'cfg.wg.keep'         = 'keep the current list'
    'cfg.wg.suggested'    = 'use the suggested apps for the profile ({0})'
    'cfg.wg.again'        = 'select again'
    'cfg.wg.none'         = 'no winget applications'
    'cfg.wg.selected'     = 'Selected ({0}): {1}'
    'cfg.wg.done'         = 'Winget.Install: {0} applications'

    'cfg.save'            = 'Saving the manifest'
    'cfg.done'            = 'Configuration saved. Next: -Mode Download (free packages), -Mode PackageList (plan), then -Mode Update or the build: Optimize -> Generalize'
}
