@{
    'dl.step'           = 'DOWNLOAD - freely available packages (Microsoft, VMware) into C:\install'
    'dl.catalog'        = 'Catalog: {0}'
    'dl.indexEmpty'     = 'No matching file in the listing {0}'
    'dl.from'           = 'Source: {0}'
    'dl.noSigCheck'     = '{0}: no Authenticode check (Windows verifies the MSIX signature at install)'
    'dl.badSig'         = '{0}: invalid signature ({1}, {2}) - file rejected'
    'dl.current'        = '{0}: already current'
    'dl.saved'          = '{0}: saved ({1} MB)'
    'dl.oldRemoved'     = 'Older version removed: {0}'
    'dl.notInZip'       = '{0} not found in {1}'
    'dl.zipChecked'     = 'Signatures of {0} files in the archive are valid'
    'dl.failed'         = '[{0}] download failed: {1}'
    'dl.summary'        = 'Summary'
    'dl.counts'         = 'New: {0}, already current: {1}, failed: {2}'
    'dl.manual'         = 'Download manually (login or version choice required) - see docs/downloads.md:'
    'dl.manual.osot'    = 'Omnissa Horizon OS Optimization Tool (OSOT) -> OSOT\'
    'dl.manual.agents'  = 'Omnissa Horizon Agent, Dynamic Environment Manager, App Volumes Agent (versions matching the backend) -> Horizon\'
    'dl.manual.patches' = 'Windows cumulative updates (MSU) from the Microsoft Update Catalog -> Patches\'
    'dl.manual.nvidia'  = 'NVIDIA vGPU guest driver and license token (Graphics profile only)'
    'dl.someFailed'     = '{0} download(s) failed - check the warnings above'

    'osot.toolCopied'   = '{0} copied to {1} (required by OSOT Finalize {2})'
    'osot.toolMissing'  = 'OSOT Finalize {0} needs {1} - not found (run -Mode Download)'
}
