@{
    'inv.partial'            = 'incomplete block: {0}'
    'inv.detected'           = 'detected: {0}'
    'inv.step'               = 'INVENTORY - packages and auto-update blocking status'
    'inv.wingetLater'        = 'winget export runs from the administrator account after the SYSTEM task'
    'inv.summary'            = 'Summary'
    'inv.status.Blocked'     = 'Blocked'
    'inv.status.Active'      = 'ACTIVE'
    'inv.status.NoUpdater'   = 'No updater'
    'inv.status.NotDetected' = 'Not detected'
    'inv.active'             = 'Packages with ACTIVE automatic updates:'
    'inv.allBlocked'         = 'All detected auto-update mechanisms are blocked'
    'inv.report'             = 'Report: {0}'

    'status.step'       = 'STATUS of the update mechanisms'
    'status.none'       = '<none>'
    'status.yes'        = 'yes'
    'status.tasks'      = 'Update tasks: {0}, active: {1}'
    'status.taskActive' = '  active: {0}'
    'status.fileActive' = 'Updater active: {0}'
    'status.m365'       = 'Microsoft 365 version: {0}'
    'status.pending'    = 'Pending reboot: {0}'
    'status.noPending'  = 'No pending reboot'
    'status.sealed'     = 'Image SEALED (since {0})'
    'status.baseline'   = 'Only the baseline is saved ({0}) - Seal not finished'
    'status.notSealed'  = 'Image is NOT sealed (no state record)'
}
