@{
    # --- package platform ---
    'pkg.noInstallDir'   = 'Folder {0} does not exist'
    'pkg.createDefault'  = 'Manifest {0} not found - creating the default one (Horizon components disabled, to be completed)'
    'pkg.jsonError'      = 'JSON syntax error in {0}: {1}'
    'pkg.unzip'          = 'Extracting {0}'
    'pkg.readHotfix'     = 'Reading installed updates (Get-HotFix + Get-WindowsPackage)...'
    'pkg.noOdtXml'       = '[{0}] no ODT configuration XML next to {1}'
    'pkg.unknownType'    = '[{0}] unknown type ''{1}'''
    'pkg.okReboot'       = '[{0}] {1}: OK, reboot required (code {2})'
    'pkg.ok'             = '[{0}] {1}: OK (code {2})'
    'pkg.error'          = '[{0}] {1}: ERROR code {2} (0x{3:X8}), log: {4}'
    'pkg.stepPlan'       = 'PACKAGES - install plan (dry run)'
    'pkg.stepInstall'    = 'PACKAGES - installing from the manifest'
    'pkg.manifest'       = 'Manifest: {0}'
    'pkg.nothing'        = 'No packages to install'
    'pkg.needsReboot'    = '[{0}] needs a reboot before the next packages'
    'pkg.summary'        = 'Packages: installed {0}, errors {1}'
    'pkg.allAssigned'    = 'Every package in {0} has a manifest entry (or is on the Ignore list)'
    'pkg.unassigned'     = 'Files in {0} WITHOUT a manifest entry (will not be installed) - run -Mode Discover:'

    'plan.none'                  = '(none)'
    'plan.noId'                  = '(no Id)'
    'plan.byChannel'             = 'per channel'
    'plan.action.install'        = 'install'
    'plan.action.update'         = 'update'
    'plan.action.skip'           = 'skip'
    'plan.action.current'        = 'current'
    'plan.action.missing'        = 'file missing'
    'plan.reason.requireInstalled' = 'not installed (RequireInstalled)'
    'plan.reason.new'            = 'new installation'
    'plan.reason.noVersion'      = 'cannot read the package version (add "Version" to the manifest)'
    'plan.reason.disabledTag'    = '(disabled)'
    'plan.reason.noOdtXml'       = 'no ODT configuration XML (<Add>) next to setup.exe and no file from the Config field'
    'plan.reason.always'         = 'always runs'
    'plan.reason.disabled'       = 'disabled in the manifest (would be: {0})'
    'plan.reason.notSelected'    = 'not in -PackageIds (would be: {0})'

    # --- discover ---
    'disc.step'         = 'DISCOVER - manifest matching the current image and the contents of C:\install'
    'disc.complete'     = 'No new files to describe - the manifest is complete'
    'disc.x86'          = 'x86 variant (x64 image)'
    'disc.patchName'    = '{0} patches from {1}'
    'disc.rootDir'      = 'the root folder'
    'disc.newOn'        = 'new entry (enabled)'
    'disc.newOff'       = 'new entry (disabled)'
    'disc.byKb'         = 'patches by KB'
    'disc.skipped'      = 'skipped'
    'disc.archive'      = 'archive/unknown type - describe it manually (Archive field)'
    'disc.exeNote'      = 'fill in the silent install arguments, then set Enabled=true'
    'disc.installed'    = 'installed: {0} {1}'
    'disc.notInstalled' = 'not installed in the image'
    'disc.infra'        = 'VDI component - enable deliberately'
    'disc.proposals'    = 'Proposals'
    'disc.applied'      = 'Manifest updated: {0}'
    'disc.saved'        = 'Proposal saved: {0}'
    'disc.applyHint'    = 'Review it and apply: -Mode Discover -Apply (the current manifest is backed up)'

    # --- init ---
    'init.step'           = 'INIT - folder structure {0}'
    'init.patches'        = 'Windows patches *.msu / *.cab (by KB) and application patches *.msp'
    'init.office'         = 'Office Deployment Tool: setup.exe + Configuration_x64.xml (downloads go to Office\Data)'
    'init.fslogix'        = 'FSLogix_*.zip, the official Microsoft package'
    'init.horizon'        = 'VMware Tools, Horizon Agent, DEM, App Volumes Agent (manifest entries Enabled=false)'
    'init.osot'           = 'Omnissa OS Optimization Tool (*.exe) + Optimize.json (Export Selections), LGPO.exe, sdelete64.exe'
    'init.teams'          = 'teamsbootstrapper.exe + MSTeams-x64.msix'
    'init.apps'           = 'own MSI/EXE/MSIX applications'
    'init.scripts'        = 'PS1 configuration scripts'
    'init.created'        = 'Created {0}'
    'init.exists'         = 'Exists   {0}'
    'init.readmeTitle'    = 'Structure of {0} (VDI-ImageMaint)'
    'init.readmeStart'    = 'start here (menu)'
    'init.readmeScript'   = 'the tool'
    'init.readmeManifest' = 'package manifest + OSOT configuration ("Osot" section)'
    'init.readmeRecursive'= 'Files can be in any subfolder - the search is recursive.'
    'init.readmeList'     = 'Files without a manifest entry are shown by: .\VDI-ImageMaint.ps1 -Mode PackageList'
    'init.readme'         = 'Structure description: {0}'
    'init.noMove'         = 'Existing files are not moved - they can stay where they are.'
}
