@{
    'bld.stage'            = 'Build stage: {0}'
    'bld.appxRemoved'      = 'AppX removed: {0}'
    'bld.encrypted'        = 'Drive {0} is encrypted (status {1}, {2}%) - decrypting (manage-bde -off)'
    'bld.decrypting'       = '  decrypting: status {0}, {1}% left'
    'bld.remediation'      = 'Fixing known Sysprep blockers'
    'bld.noEncryption'     = 'PreventDeviceEncryption=1, BDESVC disabled'
    'bld.stillEncrypted'   = 'Drive {0} is still encrypted - Sysprep would fail'
    'bld.teamsUser'        = 'MSTeams is installed for the account only - provision it: teamsbootstrapper.exe -p (not removed)'
    'bld.appxUser'         = 'AppX for the account only: {0} (remove it or use -RemoveUnprovisionedAppx)'
    'bld.noCheckerForce'   = 'Test-SysprepReadiness.ps1 not found - continuing without the check (-Force)'
    'bld.noChecker'        = 'Test-SysprepReadiness.ps1 not found (copy it to C:\install\Scripts). -Force skips the check.'
    'bld.check'            = 'Readiness check: {0}'
    'bld.checkFailForce'   = 'Readiness check: FAIL - continuing (-Force)'
    'bld.checkFail'        = 'Readiness check: FAIL (report: {0}). Remove the causes and run again.'
    'bld.checkCode'        = 'Readiness check: code {0} (0 = OK, 1 = warnings)'
    'bld.pwd'              = 'Password of the {0} account after Generalize (AutoLogon to finish the build)'
    'bld.pwdRepeat'        = 'Repeat the password'
    'bld.pwdMismatch'      = 'Passwords differ or are empty - try again'
    'bld.pwdNone'          = 'No administrator password given'
    'bld.step'             = 'GENERALIZE - Sysprep of the golden image (build, once per Windows release)'
    'bld.notSystem'        = 'Run Generalize from the administrator account (OSOT does not work as SYSTEM).'
    'bld.noAuditForce'     = 'The system is NOT in audit mode - continuing (-Force)'
    'bld.noAudit'          = 'The system is not in audit mode (required by OSOT Generalize). Build from an ISO: press Ctrl+Shift+F3 at the first OOBE screen. -Force skips the check.'
    'bld.snapshot'         = 'Take a VM snapshot "pre-generalize" (a failed Sysprep can be irreversible) and run again with -SnapshotConfirmed.'
    'bld.pending'          = 'A reboot is pending ({0}) - Sysprep fails with 0x36b7. Reboot and run again.'
    'bld.noOsot'           = 'OSOT not found in {0} (or use -GeneralizeEngine Sysprep).'
    'bld.oobe'             = 'OOBE settings: time zone={0}, UI={1}, system={2}, user={3}, keyboard={4}, name={5}'
    'bld.cmdTooLong'       = 'FirstLogonCommands command too long ({0} characters)'
    'bld.sysprepFailed'    = 'Sysprep did not finish correctly (ImageState={0}). Details: {1} and setupact.log. Restore the snapshot if the VM does not start.'
    'bld.sysprepOk'        = 'Sysprep finished successfully. Reboot -> OOBE (unattend) -> AutoLogon -> PostGeneralize'
    'bld.autologonOff'     = 'AutoLogon disabled, password removed from Winlogon'
    'bld.postStep'         = 'POST-GENERALIZE - finishing the image build after OOBE'
    'bld.removed'          = 'Removed {0}'
    'bld.unexpectedStage'  = 'Build stage: ''{0}'' (expected Generalized) - continuing'
    'bld.appxWait'         = 'Waiting {0} s for AppX provisioning after the first logon (Omnissa recommendation)'
    'bld.agents'           = 'Agents after Generalize: {0}'
    'bld.manifestError'    = 'Manifest error - build stopped'
    'bld.pendingBeforeSeal'= 'A reboot is pending ({0}) before Seal'
    'bld.done'             = 'Image build finished: Generalize -> agents -> Seal -> Finalize'

    'sys.start'            = 'Running {0} as SYSTEM...'
    'sys.log'              = 'Log: {0}'
}
