@{
    # --- common ---
    'appdiff.step'    = 'Changes in installed applications'
    'appdiff.none'    = 'No application version changes'
    'appdiff.new'     = '(new)'
    'appdiff.removed' = '(removed)'
    'file.backup'     = 'Backup: {0}'
    'file.saved'      = 'Saved: {0}'

    # --- update mechanisms (Inventory) ---
    'upd.firefox'   = 'DisableAppUpdate + MozillaMaintenance + Background Update task'
    'upd.mozmaint'  = 'MozillaMaintenance service'
    'upd.chrome'    = 'Google\Update policy + GoogleUpdater/gupdate services + tasks'
    'upd.edge'      = 'edgeupdate services + MicrosoftEdgeUpdateTask tasks'
    'upd.vscode'    = 'VSCode policy UpdateMode=none'
    'upd.vs'        = 'BackgroundDownloadDisabled + VisualStudio\Updates tasks'
    'upd.office'    = 'officeupdate EnableAutomaticUpdates=0 + Office Automatic Updates tasks'
    'upd.onedrive'  = 'OneDrive Update tasks'
    'upd.adobe'     = 'FeatureLockDown bUpdater=0 + AdobeARMservice service + Adobe Acrobat Update task'
    'upd.klite'     = 'K-Lite tasks (turn off the update check in Codec Tweak Tool manually)'
    'upd.vdi'       = 'manual update, matching the VDI backend version'
    'upd.none'      = 'no own updater (Windows Update / winget / manual)'
    'upd.wu'        = 'NoAutoUpdate + wuauserv/UsoSvc/WaaSMedicSvc + WindowsUpdate/UpdateOrchestrator tasks'
    'upd.sys.wu'    = 'Windows Update'
    'upd.sys.store' = 'Microsoft Store (MSIX app updates)'

    # --- winget ---
    'winget.register'         = 'winget not found - trying to register App Installer for the current account'
    'winget.registerFailed'   = 'Registration failed: {0}'
    'winget.missing'          = 'winget is not available. Install "App Installer" (Microsoft.DesktopAppInstaller) - OSOT/LTSC often removes it.'
    'winget.sourceUpdate'     = 'winget source update: code {0}'
    'winget.header'           = 'winget table header not recognized: ''{0}'''
    'winget.skip.truncated'   = 'truncated identifier'
    'winget.skip.store'       = 'MSIX/Store - winget updates it for the current account only'
    'winget.skip.teams'       = 'MSIX - updated by teamsbootstrapper'
    'winget.skip.excluded'    = 'excluded (VDI component / own update path)'
    'winget.action.update'    = 'update'
    'winget.action.skip'      = 'skip'
    'winget.list.step'        = 'WINGET - available updates (dry run)'
    'winget.none'             = 'No winget updates available'
    'winget.list.summary'     = 'To update: {0}, skipped: {1}'
    'winget.list.current'     = '(current or not installed)'
    'winget.list.hint'        = 'List mode (-WingetIds + Winget.Install). Add -WingetAll to see all packages.'
    'winget.install.plan'     = 'winget apps from the manifest (plan)'
    'winget.install.step'     = 'winget apps from the manifest - installing missing ones'
    'winget.system'           = 'winget does not work properly as SYSTEM - skipped'
    'winget.installed'        = '{0}: installed'
    'winget.toInstall'        = '{0}: to be installed'
    'winget.install.ok'       = '{0}: installed now'
    'winget.install.already'  = '{0}: already installed'
    'winget.install.noMachine'= '{0}: no machine-wide installer (--scope machine) - skipped; a per-user install makes no sense on VDI'
    'winget.install.failed'   = '{0}: install failed, code {1} (0x{1:X8})'
    'winget.upd.ok'           = '{0}: updated'
    'winget.upd.current'      = '{0}: up to date'
    'winget.upd.notInstalled' = '{0}: not installed - skipped'
    'winget.upd.code'         = '{0}: code {1} (0x{1:X8})'
    'winget.upd.stepAll'      = 'Apps via winget (everything detected, with exclusions)'
    'winget.upd.stepList'     = 'Apps via winget (-WingetIds list + Winget.Install from the manifest)'
    'winget.upd.skipped'      = '{0}: skipped (WingetExcludeIds / Store)'
    'winget.upd.skip'         = 'Skipped: {0} [{1}] - {2}'
    'winget.upd.summary'      = 'winget: updated {0}, errors {1}, skipped {2}'
    'winget.upd.left'         = 'Still to update: {0}'
    'winget.export.ok'        = 'winget export: {0}'
    'winget.export.failed'    = 'winget export failed (code {0})'
}
