@{
    'seal.step'            = 'SEAL - blocking automatic updates'
    'seal.baseline'        = 'Baseline before OSOT saved: {0}'
    'seal.policy'          = 'Policy: {0}\{1} = {2}'
    'seal.svc.missing'     = 'Service {0} does not exist - skipped'
    'seal.svc.disabled'    = 'Service {0}: Disabled (was Start={1})'
    'seal.svc.protected'   = 'Service {0}: no permission to change it (protected) - run with -AsSystem'
    'seal.svc.stopFailed'  = 'Service {0}: could not be stopped ({1})'
    'seal.task.disabled'   = 'Task disabled: {0}'
    'seal.task.protected'  = 'Protected task, not disabled: {0} (use -AsSystem)'
    'seal.type.Task'       = 'Task'
    'seal.type.Service'    = 'Service'
    'seal.detect.none'     = 'No additional updaters detected'
    'seal.detect.reportOnly' = 'Detected (NOT blocked, -NoBlockDetected): [{0}] {1} -> {2}'
    'seal.detect.found'    = 'Detected: [{0}] {1} -> {2}'
    'seal.file.disabled'   = 'Updater disabled: {0}'
    'seal.pendingReboot'   = 'A reboot is pending ({0}). Reboot the VM before Seal - otherwise the pending operations run on every clone. (-Force skips the check)'
    'seal.pendingWarn'     = 'Note: pending reboot ({0})'
    'seal.already'         = 'The image was already sealed ({0}) - adding missing items'
    'seal.fromBaseline'    = 'Baseline from {0} - continuing Seal'
    'seal.sec.policies'    = 'Policies'
    'seal.sec.services'    = 'Services'
    'seal.sec.tasks'       = 'Scheduled tasks'
    'seal.sec.files'       = 'Application updaters'
    'seal.sec.detect'      = 'Detecting other update mechanisms'
    'seal.stateSaved'      = 'State saved: {0}'
    'seal.doneWarn'        = 'Seal finished with {0} warnings - run again with -AsSystem'
    'seal.done'            = 'Seal finished successfully'
    'seal.next'            = 'Next: shut down the VM -> snapshot -> Horizon Console: Push Image (Instant Clone)'

    'cleanup.step'         = 'Image cleanup'
    'cleanup.sd'           = 'SoftwareDistribution\Download cleared'
    'cleanup.do'           = 'Delivery Optimization cache cleared'
    'cleanup.doSkipped'    = 'Delivery Optimization cache - skipped'
    'cleanup.temp'         = 'TEMP folders cleared'
    'cleanup.dism'         = 'DISM /StartComponentCleanup (can take several minutes)...'
    'cleanup.dismDone'     = 'DISM finished, code: {0}'

    'unlock.step'          = 'UNLOCK - restoring update mechanisms'
    'unlock.noState'       = 'No Seal state saved - restoring only the values set by this tool'
    'unlock.policyRemoved' = 'Policy removed: {0}'
    'unlock.svc'           = 'Service {0}: Start={1}'
    'unlock.svcDenied'     = 'Service {0}: no permission (-AsSystem)'
    'unlock.file'          = 'Restored: {0}'
    'unlock.tasksUnknown'  = 'Scheduled tasks left unchanged (original state unknown)'
    'unlock.policy'        = 'Policy restored: {0}'
    'unlock.policyFailed'  = 'Policy {0}: {1}'
    'unlock.task'          = 'Task enabled: {0}'
    'unlock.taskDenied'    = 'Task {0}: not enabled (-AsSystem)'
    'unlock.done'          = 'State fully restored, Seal record removed'
    'unlock.partial'       = 'Restored with {0} problems - state record kept, run Unlock with -AsSystem'
}
