@{
    'upd.rebootManual'       = 'Reboot the VM and run the same command again - installed items will be skipped (or use -AutoReboot).'
    'upd.maxRounds'          = 'Reached the limit of {0} reboots (-MaxRounds) - stop and check the logs'
    'upd.resume'             = 'Resume after logon of {0} (round {1}/{2}): {3}'
    'upd.rebootIn'           = 'Rebooting in {0} s (Ctrl+C to cancel)...'
    'upd.defender'           = 'Microsoft Defender - signatures'
    'upd.defenderOk'         = 'Signatures updated'
    'upd.defenderSkip'       = 'Defender skipped ({0})'
    'upd.unlockSystem'       = 'Some blocks are protected - running Unlock again as SYSTEM'
    'upd.unlockSystemFailed' = 'Unlock as SYSTEM: code {0} - Windows Update may not work, check Status'
    'upd.infra'              = 'VDI components (updated only by enabled manifest packages)'
    'upd.rebootNext'         = 'Reboot required ({0}) - next Update round after the reboot'
    'upd.rebootRequired'     = 'Reboot required ({0}). After the reboot run -Mode Update again until there is nothing new.'
    'upd.sealSkipped'        = 'Seal skipped (-ThenSeal) - the image needs a reboot'
    'upd.pendingFiles'       = 'Pending file operations ({0}) - they do not block Seal'
    'upd.thenSeal'           = 'Update finished - sealing the image'
    'upd.sealFailed'         = 'Seal (SYSTEM) finished with code {0} - check the Seal_*.log log'
    'upd.noReboot'           = 'No pending reboot. Next step: -Mode Seal [-Cleanup] -AsSystem -Shutdown'

    'odt.xmlError'        = 'ODT configuration: XML error ({0})'
    'odt.noAdd'           = 'ODT configuration: no <Add> element'
    'odt.info'            = 'ODT configuration: channel={0}, SourcePath={1}, version={2}'
    'odt.latest'          = 'latest in the channel'
    'odt.updatesOn'       = 'ODT configuration: <Updates Enabled="TRUE"> - FALSE is recommended on VDI'
    'odt.noScl'           = 'ODT configuration: SharedComputerLicensing=1 missing (required on shared VDI)'
    'odt.noForce'         = 'ODT configuration: FORCEAPPSHUTDOWN=TRUE missing - open Office apps can block the update'
    'odt.display'         = 'ODT configuration: <Display Level="None"> recommended for an unattended install'
    'odt.start'           = 'Office Deployment Tool: {0} (version before: {1})'
    'odt.download'        = 'ODT /download (downloading the installation files)...'
    'odt.downloadFailed'  = 'ODT /download: code {0} (logs: %TEMP%\*.log)'
    'odt.downloadOk'      = 'ODT /download finished'
    'odt.configure'       = 'ODT /configure (install/update)...'
    'odt.configureFailed' = 'ODT /configure: code {0} (logs: %TEMP%\*.log)'
    'odt.unchanged'       = 'Microsoft 365: version unchanged ({0}) - current for the configured channel'

    'c2r.step'      = 'Microsoft 365 Apps (C2R client - no active ODT package in the manifest)'
    'c2r.missing'   = 'Microsoft 365 C2R not found - skipped'
    'c2r.before'    = 'Version before: {0} (channel: {1})'
    'c2r.unchanged' = 'Microsoft 365: no version change after {0} min (current, or updating in the background - check Status before Seal)'

    'vs.missing' = 'Visual Studio Installer not found - skipped'
    'vs.update'  = 'Updating: {0}'
    'vs.ok'      = 'Visual Studio updated'
    'vs.reboot'  = 'Visual Studio updated - reboot required'
    'vs.code'    = 'Visual Studio: exit code {0} (logs: %TEMP%\dd_*.log)'

    'edge.missing' = 'EdgeUpdate not found - skipped'
    'edge.ok'      = 'EdgeUpdate started'

    'teams.step'           = 'Microsoft Teams (new, MSIX) - updating the provisioned version'
    'teams.notProvisioned' = 'New Teams is not provisioned in the image - skipped'
    'teams.before'         = 'Provisioned version before: {0}'
    'teams.download'       = 'Downloading teamsbootstrapper.exe...'
    'teams.downloadFailed' = 'Could not download teamsbootstrapper: {0} (use -TeamsBootstrapperPath)'
    'teams.badSignature'   = 'teamsbootstrapper: invalid signature - not running {0}'
    'teams.result'         = 'teamsbootstrapper -p: code {0} {1}'
    'teams.current'        = 'Teams: provisioned version unchanged (current)'
    'teams.failed'         = 'Teams: update failed - check the output above'

    'wu.step'        = 'Windows Update (the search can take several minutes)'
    'wu.disabled'    = 'wuauserv is still disabled (e.g. by OSOT) - setting Manual for the update'
    'wu.cannotChange'= 'Cannot change wuauserv'
    'wu.searchError' = 'Windows Update: search error ({0})'
    'wu.none'        = 'No new Windows updates'
    'wu.downloading' = 'Downloading...'
    'wu.installing'  = 'Installing...'
    'wu.result'      = 'Windows Update: {0}, reboot required: {1}'
}
