@{
    'bld.stage'            = 'Etap budowy: {0}'
    'bld.appxRemoved'      = 'AppX usunięty: {0}'
    'bld.encrypted'        = 'Dysk {0} zaszyfrowany (status {1}, {2}%) - odszyfrowuję (manage-bde -off)'
    'bld.decrypting'       = '  odszyfrowywanie: status {0}, pozostało {1}%'
    'bld.remediation'      = 'Naprawa znanych blokerów Sysprep'
    'bld.noEncryption'     = 'PreventDeviceEncryption=1, BDESVC wyłączona'
    'bld.stillEncrypted'   = 'Dysk {0} nadal zaszyfrowany - Sysprep się nie powiedzie'
    'bld.teamsUser'        = 'MSTeams zainstalowany tylko dla konta - zaprowizjonuj: teamsbootstrapper.exe -p (nie usuwam)'
    'bld.appxUser'         = 'AppX tylko dla konta: {0} (usuń lub użyj -RemoveUnprovisionedAppx)'
    'bld.noCheckerForce'   = 'Brak Test-SysprepReadiness.ps1 - kontynuuję bez kontroli (-Force)'
    'bld.noChecker'        = 'Brak Test-SysprepReadiness.ps1 (skopiuj go do C:\install\Scripts). -Force pomija kontrolę.'
    'bld.check'            = 'Kontrola gotowości: {0}'
    'bld.checkFailForce'   = 'Kontrola gotowości: FAIL - kontynuuję (-Force)'
    'bld.checkFail'        = 'Kontrola gotowości: FAIL (raport: {0}). Usuń przyczyny i uruchom ponownie.'
    'bld.checkCode'        = 'Kontrola gotowości: kod {0} (0 = OK, 1 = ostrzeżenia)'
    'bld.pwd'              = 'Hasło konta {0} po Generalize (AutoLogon do dokończenia budowy)'
    'bld.pwdRepeat'        = 'Powtórz hasło'
    'bld.pwdMismatch'      = 'Hasła różne lub puste - spróbuj ponownie'
    'bld.pwdNone'          = 'Nie podano hasła administratora'
    'bld.step'             = 'GENERALIZE - Sysprep obrazu wzorcowego (budowa, raz na wydanie Windows)'
    'bld.notSystem'        = 'Generalize uruchamiaj z konta administratora (OSOT nie działa jako SYSTEM).'
    'bld.noAuditForce'     = 'System NIE jest w trybie audytu - kontynuuję (-Force)'
    'bld.noAudit'          = 'System nie jest w trybie audytu (OSOT Generalize tego wymaga). Buduj z ISO: Ctrl+Shift+F3 na pierwszym ekranie OOBE. -Force pomija sprawdzenie.'
    'bld.snapshot'         = 'Zrób snapshot VM "pre-generalize" (nieudany Sysprep bywa nieodwracalny) i uruchom ponownie z -SnapshotConfirmed.'
    'bld.pending'          = 'Oczekuje restart ({0}) - Sysprep kończy się błędem 0x36b7. Zrestartuj i uruchom ponownie.'
    'bld.noOsot'           = 'Brak OSOT w {0} (albo użyj -GeneralizeEngine Sysprep).'
    'bld.oobe'             = 'Ustawienia OOBE: strefa={0}, UI={1}, system={2}, użytkownik={3}, klawiatura={4}, nazwa={5}'
    'bld.cmdTooLong'       = 'Polecenie FirstLogonCommands za długie ({0} znaków)'
    'bld.sysprepFailed'    = 'Sysprep nie zakończył się poprawnie (ImageState={0}). Szczegóły: {1} i setupact.log. Przywróć snapshot, jeśli VM nie startuje.'
    'bld.sysprepOk'        = 'Sysprep zakończony poprawnie. Restart -> OOBE (unattend) -> AutoLogon -> PostGeneralize'
    'bld.autologonOff'     = 'AutoLogon wyłączony, hasło usunięte z Winlogon'
    'bld.postStep'         = 'POST-GENERALIZE - dokończenie budowy obrazu po OOBE'
    'bld.removed'          = 'Usunięto {0}'
    'bld.unexpectedStage'  = 'Etap budowy: ''{0}'' (oczekiwano Generalized) - kontynuuję'
    'bld.appxWait'         = 'Czekam {0} s na prowizjonowanie AppX po pierwszym logowaniu (zalecenie Omnissa)'
    'bld.agents'           = 'Agenty po Generalize: {0}'
    'bld.manifestError'    = 'Błąd manifestu - przerwano budowę'
    'bld.pendingBeforeSeal'= 'Oczekuje restart ({0}) przed Seal'
    'bld.done'             = 'Budowa obrazu zakończona: Generalize -> agenty -> Seal -> Finalize'

    'sys.start'            = 'Uruchamiam {0} jako SYSTEM...'
    'sys.log'              = 'Log: {0}'
}
