@{
    'inv.partial'            = 'niepełna blokada: {0}'
    'inv.detected'           = 'wykryto: {0}'
    'inv.step'               = 'INVENTORY - zrzut pakietów i stanu blokady autoaktualizacji'
    'inv.wingetLater'        = 'winget export zostanie wykonany z konta administratora po zakończeniu zadania SYSTEM'
    'inv.summary'            = 'Podsumowanie'
    'inv.status.Blocked'     = 'Zablokowana'
    'inv.status.Active'      = 'AKTYWNA'
    'inv.status.NoUpdater'   = 'Brak mechanizmu'
    'inv.status.NotDetected' = 'Nie wykryto'
    'inv.active'             = 'Pakiety z AKTYWNĄ autoaktualizacją:'
    'inv.allBlocked'         = 'Wszystkie wykryte mechanizmy autoaktualizacji są zablokowane'
    'inv.report'             = 'Raport: {0}'

    'status.step'       = 'STATUS mechanizmów aktualizacji'
    'status.none'       = '<brak>'
    'status.yes'        = 'tak'
    'status.tasks'      = 'Zadania aktualizacji: {0}, aktywne: {1}'
    'status.taskActive' = '  aktywne: {0}'
    'status.fileActive' = 'Aktualizator aktywny: {0}'
    'status.m365'       = 'Microsoft 365 wersja: {0}'
    'status.pending'    = 'Oczekujący restart: {0}'
    'status.noPending'  = 'Brak oczekującego restartu'
    'status.sealed'     = 'Obraz ZAPIECZĘTOWANY (od {0})'
    'status.baseline'   = 'Zapisany tylko stan bazowy ({0}) - Seal niedokończony'
    'status.notSealed'  = 'Obraz NIE jest zapieczętowany (brak zapisu stanu)'
}
