@{
    'upd.rebootManual'       = 'Zrestartuj VM i uruchom ponownie to samo polecenie - zainstalowane elementy zostaną pominięte (lub użyj -AutoReboot).'
    'upd.maxRounds'          = 'Osiągnięto limit {0} restartów (-MaxRounds) - przerwij i sprawdź logi'
    'upd.resume'             = 'Wznowienie po zalogowaniu {0} (runda {1}/{2}): {3}'
    'upd.rebootIn'           = 'Restart za {0} s (Ctrl+C aby przerwać)...'
    'upd.defender'           = 'Microsoft Defender - sygnatury'
    'upd.defenderOk'         = 'Sygnatury zaktualizowane'
    'upd.defenderSkip'       = 'Defender pominięty ({0})'
    'upd.unlockSystem'       = 'Część blokad jest chroniona - ponawiam Unlock w kontekście SYSTEM'
    'upd.unlockSystemFailed' = 'Unlock jako SYSTEM: kod {0} - Windows Update może nie działać, sprawdź Status'
    'upd.infra'              = 'Komponenty VDI (aktualizowane wyłącznie przez włączone pakiety manifestu)'
    'upd.rebootNext'         = 'Wymagany restart ({0}) - kolejna runda Update po restarcie'
    'upd.rebootRequired'     = 'Wymagany restart ({0}). Po restarcie uruchom ponownie -Mode Update, aż nie będzie nowych aktualizacji.'
    'upd.sealSkipped'        = 'Seal pominięty (-ThenSeal) - obraz wymaga restartu'
    'upd.pendingFiles'       = 'Oczekujące zmiany plików ({0}) - nie blokują Seal'
    'upd.thenSeal'           = 'Aktualizacja zakończona - zamykam obraz (Seal)'
    'upd.sealFailed'         = 'Seal (SYSTEM) zakończony kodem {0} - sprawdź log Seal_*.log'
    'upd.noReboot'           = 'Brak oczekującego restartu. Następny krok: -Mode Seal [-Cleanup] -AsSystem -Shutdown'

    'odt.xmlError'        = 'Konfiguracja ODT: błąd XML ({0})'
    'odt.noAdd'           = 'Konfiguracja ODT: brak elementu <Add>'
    'odt.info'            = 'Konfiguracja ODT: kanał={0}, SourcePath={1}, wersja={2}'
    'odt.latest'          = 'najnowsza w kanale'
    'odt.updatesOn'       = 'Konfiguracja ODT: <Updates Enabled="TRUE"> - na VDI zalecane FALSE'
    'odt.noScl'           = 'Konfiguracja ODT: brak SharedComputerLicensing=1 (wymagane na współdzielonym VDI)'
    'odt.noForce'         = 'Konfiguracja ODT: brak FORCEAPPSHUTDOWN=TRUE - otwarte aplikacje Office mogą zablokować aktualizację'
    'odt.display'         = 'Konfiguracja ODT: <Display Level="None"> zalecane dla instalacji bez okien'
    'odt.start'           = 'Office Deployment Tool: {0} (wersja przed: {1})'
    'odt.download'        = 'ODT /download (pobieranie plików instalacyjnych)...'
    'odt.downloadFailed'  = 'ODT /download: kod {0} (logi: %TEMP%\*.log)'
    'odt.downloadOk'      = 'ODT /download zakończony'
    'odt.configure'       = 'ODT /configure (instalacja/aktualizacja)...'
    'odt.configureFailed' = 'ODT /configure: kod {0} (logi: %TEMP%\*.log)'
    'odt.unchanged'       = 'Microsoft 365: wersja bez zmian ({0}) - aktualna dla wybranego kanału'

    'c2r.step'      = 'Microsoft 365 Apps (klient C2R - brak aktywnego pakietu ODT w manifeście)'
    'c2r.missing'   = 'Nie znaleziono Microsoft 365 C2R - pomijam'
    'c2r.before'    = 'Wersja przed: {0} (kanał: {1})'
    'c2r.unchanged' = 'Microsoft 365: bez zmiany wersji po {0} min (aktualna lub aktualizacja w tle - sprawdź Status przed Seal)'

    'vs.missing' = 'Nie znaleziono Visual Studio Installer - pomijam'
    'vs.update'  = 'Aktualizacja: {0}'
    'vs.ok'      = 'Visual Studio zaktualizowane'
    'vs.reboot'  = 'Visual Studio zaktualizowane - wymagany restart'
    'vs.code'    = 'Visual Studio: kod wyjścia {0} (logi: %TEMP%\dd_*.log)'

    'edge.missing' = 'Nie znaleziono EdgeUpdate - pomijam'
    'edge.ok'      = 'Wywołano EdgeUpdate'

    'teams.step'           = 'Microsoft Teams (nowy, MSIX) - aktualizacja wersji zaprowizjonowanej'
    'teams.notProvisioned' = 'Nowy Teams nie jest zaprowizjonowany w obrazie - pomijam'
    'teams.before'         = 'Wersja zaprowizjonowana przed: {0}'
    'teams.download'       = 'Pobieranie teamsbootstrapper.exe...'
    'teams.downloadFailed' = 'Nie udało się pobrać teamsbootstrapper: {0} (podaj -TeamsBootstrapperPath)'
    'teams.badSignature'   = 'teamsbootstrapper: nieprawidłowy podpis - nie uruchamiam {0}'
    'teams.result'         = 'teamsbootstrapper -p: kod {0} {1}'
    'teams.current'        = 'Teams: wersja zaprowizjonowana bez zmian (aktualna)'
    'teams.failed'         = 'Teams: aktualizacja nieudana - sprawdź wynik powyżej'

    'wu.step'        = 'Windows Update (wyszukiwanie może potrwać kilka minut)'
    'wu.disabled'    = 'wuauserv nadal wyłączona (np. przez OSOT) - ustawiam Manual na czas aktualizacji'
    'wu.cannotChange'= 'Nie można zmienić wuauserv'
    'wu.searchError' = 'Windows Update: błąd wyszukiwania ({0})'
    'wu.none'        = 'Brak nowych aktualizacji Windows'
    'wu.downloading' = 'Pobieranie...'
    'wu.installing'  = 'Instalacja...'
    'wu.result'      = 'Windows Update: {0}, wymagany restart: {1}'
}
