@{
    # --- wspólne ---
    'appdiff.step'    = 'Zmiany w zainstalowanych aplikacjach'
    'appdiff.none'    = 'Brak zmian w wersjach aplikacji'
    'appdiff.new'     = '(nowa)'
    'appdiff.removed' = '(usunięta)'
    'file.backup'     = 'Kopia: {0}'
    'file.saved'      = 'Zapisano: {0}'

    # --- mechanizmy aktualizacji (Inventory) ---
    'upd.firefox'   = 'DisableAppUpdate + MozillaMaintenance + zadanie Background Update'
    'upd.mozmaint'  = 'usługa MozillaMaintenance'
    'upd.chrome'    = 'polityka Google\Update + usługi GoogleUpdater/gupdate + zadania'
    'upd.edge'      = 'usługi edgeupdate + zadania MicrosoftEdgeUpdateTask'
    'upd.vscode'    = 'polityka VSCode UpdateMode=none'
    'upd.vs'        = 'BackgroundDownloadDisabled + zadania VisualStudio\Updates'
    'upd.office'    = 'officeupdate EnableAutomaticUpdates=0 + zadania Office Automatic Updates'
    'upd.onedrive'  = 'zadania OneDrive Update'
    'upd.adobe'     = 'FeatureLockDown bUpdater=0 + usługa AdobeARMservice + zadanie Adobe Acrobat Update'
    'upd.klite'     = 'zadania K-Lite (sprawdzanie aktualizacji w Codec Tweak Tool wyłącz ręcznie)'
    'upd.vdi'       = 'aktualizacja ręczna, zgodnie z wersją backendu VDI'
    'upd.none'      = 'brak własnego aktualizatora (Windows Update / winget / ręcznie)'
    'upd.wu'        = 'NoAutoUpdate + wuauserv/UsoSvc/WaaSMedicSvc + zadania WindowsUpdate/UpdateOrchestrator'
    'upd.sys.wu'    = 'Windows Update'
    'upd.sys.store' = 'Microsoft Store (aktualizacje aplikacji MSIX)'

    # --- winget ---
    'winget.register'         = 'Nie znaleziono winget - próba rejestracji App Installer dla bieżącego konta'
    'winget.registerFailed'   = 'Rejestracja nieudana: {0}'
    'winget.missing'          = 'winget niedostępny. Zainstaluj "App Installer" (Microsoft.DesktopAppInstaller) - OSOT/LTSC często go usuwa.'
    'winget.sourceUpdate'     = 'winget source update: kod {0}'
    'winget.header'           = 'Nie rozpoznano nagłówka tabeli winget: ''{0}'''
    'winget.skip.truncated'   = 'obcięty identyfikator'
    'winget.skip.store'       = 'MSIX/Store - winget aktualizuje tylko dla bieżącego konta'
    'winget.skip.teams'       = 'MSIX - aktualizacja przez teamsbootstrapper'
    'winget.skip.excluded'    = 'wykluczenie (komponent VDI / własna ścieżka aktualizacji)'
    'winget.action.update'    = 'aktualizuj'
    'winget.action.skip'      = 'pomiń'
    'winget.list.step'        = 'WINGET - dostępne aktualizacje (podgląd)'
    'winget.none'             = 'Brak dostępnych aktualizacji winget'
    'winget.list.summary'     = 'Do aktualizacji: {0}, pominięte: {1}'
    'winget.list.current'     = '(aktualna lub niezainstalowana)'
    'winget.list.hint'        = 'Tryb listy (-WingetIds + Winget.Install). Dodaj -WingetAll, aby zobaczyć wszystkie pakiety.'
    'winget.install.plan'     = 'Aplikacje winget z manifestu (plan)'
    'winget.install.step'     = 'Aplikacje winget z manifestu - instalacja brakujących'
    'winget.system'           = 'winget nie działa poprawnie jako SYSTEM - pomijam'
    'winget.installed'        = '{0}: zainstalowany'
    'winget.toInstall'        = '{0}: do instalacji'
    'winget.install.ok'       = '{0}: zainstalowano'
    'winget.install.already'  = '{0}: już zainstalowany'
    'winget.install.noMachine'= '{0}: brak instalatora dla całej maszyny (--scope machine) - pomijam; instalacja per użytkownik nie ma sensu na VDI'
    'winget.install.failed'   = '{0}: instalacja nieudana, kod {1} (0x{1:X8})'
    'winget.upd.ok'           = '{0}: zaktualizowano'
    'winget.upd.current'      = '{0}: wersja aktualna'
    'winget.upd.notInstalled' = '{0}: nie jest zainstalowany - pomijam'
    'winget.upd.code'         = '{0}: kod {1} (0x{1:X8})'
    'winget.upd.stepAll'      = 'Aplikacje przez winget (wszystkie wykryte, z wykluczeniami)'
    'winget.upd.stepList'     = 'Aplikacje przez winget (lista -WingetIds + Winget.Install z manifestu)'
    'winget.upd.skipped'      = '{0}: pominięty (WingetExcludeIds / Store)'
    'winget.upd.skip'         = 'Pominięto: {0} [{1}] - {2}'
    'winget.upd.summary'      = 'winget: zaktualizowano {0}, błędy {1}, pominięte {2}'
    'winget.upd.left'         = 'Nadal do aktualizacji: {0}'
    'winget.export.ok'        = 'winget export: {0}'
    'winget.export.failed'    = 'winget export nieudany (kod {0})'
}
