@{
    'cfg.default'    = 'domyślnie'
    'cfg.choice'     = 'Wybór 1-{0} [Enter = {1}]'
    'cfg.yn'         = 'T/n'
    'cfg.ny'         = 't/N'
    'cfg.yes'        = 'tak'
    'cfg.on'         = 'włączone'
    'cfg.off'        = 'wyłączone'
    'cfg.kept'       = 'zachowany'
    'cfg.unchanged'  = 'bez zmian'
    'cfg.confirm'    = 'Zatwierdzić?'
    'cfg.noGrid'     = 'Out-GridView niedostępny ({0}) - wybór w konsoli'
    'cfg.numbers'    = 'Numery oddzielone przecinkami, zakresy 1-5, * = wszystkie, Enter = żadna'

    'cfg.step'       = 'CONFIGURE - kreator konfiguracji obrazu'
    'cfg.notSystem'  = 'Configure uruchamiaj interaktywnie z konta administratora.'
    'cfg.step1'      = 'Krok 1/8: profil'
    'cfg.profile'    = 'Profil obrazu:'
    'cfg.profile.uni'= 'Uczelnia (University) - laboratoria, studenci i pracownicy'
    'cfg.profile.bus'= 'Firma (Business) - pracownicy biurowi, intensywne Teams, dane w OneDrive'
    'cfg.profile.gfx'= 'Grafik / projektant (Graphics) - vGPU, pełne efekty wizualne, akceleracja GPU w aplikacjach'

    'cfg.step2'           = 'Krok 2/8: Microsoft 365 Apps (Office Deployment Tool)'
    'cfg.noOffice'        = 'Brak wpisu Office365 w manifeście - pomijam'
    'cfg.oldXmlBad'       = 'Istniejący {0}: błąd XML - zostanie zastąpiony'
    'cfg.license'         = 'Licencja Microsoft 365 (Shared Computer Activation działa tylko z tymi planami):'
    'cfg.license.ent'     = 'Microsoft 365 Apps for enterprise / education (O365ProPlusRetail) - E3/E5, A3/A5'
    'cfg.license.bus'     = 'Microsoft 365 Apps for business (O365BusinessRetail) - WYŁĄCZNIE Business Premium'
    'cfg.channel'         = 'Kanał aktualizacji (obraz aktualizujesz sam w cyklu Update):'
    'cfg.channel.mec'     = 'MonthlyEnterprise - raz w miesiącu, przewidywalny (zalecany dla VDI)'
    'cfg.channel.cc'      = 'Current - najnowsze funkcje, częstsze zmiany'
    'cfg.channel.sac'     = 'SemiAnnual - dwa razy w roku, najstabilniejszy'
    'cfg.lang'            = 'Główny język Office:'
    'cfg.lang.pl'         = 'polski (pl-pl)'
    'cfg.lang.en'         = 'angielski (en-us)'
    'cfg.lang.de'         = 'niemiecki (de-de)'
    'cfg.lang.fr'         = 'francuski (fr-fr)'
    'cfg.lang.plen'       = 'polski + angielski (pl-pl + en-us, oba pełne)'
    'cfg.lang.other'      = 'inny język (wpisz kod)'
    'cfg.lang.code'       = 'Kod języka Office (np. it-it, cs-cz, uk-ua)'
    'cfg.lang2'           = 'Drugi język:'
    'cfg.lang2.none'      = 'brak (jeden język - najmniejszy obraz, najszybsza aktualizacja)'
    'cfg.lang2.proof'     = 'tylko narzędzia sprawdzające (ProofingTools) - pisownia w drugim języku'
    'cfg.lang2.full'      = 'pełny pakiet językowy (interfejs + pisownia)'
    'cfg.lang2.code'      = 'Drugi język'
    'cfg.app.access'      = 'Microsoft Access'
    'cfg.app.onenote'     = 'OneNote (wersja desktopowa)'
    'cfg.app.publisher'   = 'Publisher - Microsoft wycofuje go w październiku 2026, zalecane wykluczenie'
    'cfg.app.outlook'     = 'Outlook (klasyczny)'
    'cfg.excludedNow'     = 'Obecnie wykluczone: {0}'
    'cfg.excludeTitle'    = 'Zaznacz aplikacje do WYKLUCZENIA z obrazu (Ctrl = wiele)'

    'cfg.stepJava'        = 'Krok 3/8: programowanie w Javie (Temurin JDK + Eclipse IDE)'
    'cfg.java.enable'     = 'Zainstalować narzędzia do Javy (Temurin JDK + Eclipse IDE)?'
    'cfg.java.off'        = 'Pakiety Java/Eclipse wyłączone (już zainstalowane wersje zostają w obrazie, tylko nie są aktualizowane)'
    'cfg.java.jdk'        = 'Które JDK? (pierwsze ustawia JAVA_HOME, PATH i .jar)'
    'cfg.java.jdk.both'   = 'Temurin 21 + 25 LTS (JAVA_HOME = 21)'
    'cfg.java.jdk.21'     = 'Tylko Temurin 21 LTS'
    'cfg.java.jdk.25'     = 'Tylko Temurin 25 LTS'
    'cfg.java.pkg'        = 'Pakiet Eclipse'
    'cfg.java.pkg.java'   = 'Eclipse IDE for Java Developers'
    'cfg.java.pkg.jee'    = 'Eclipse IDE for Enterprise Java and Web Developers (ZIP pobierany ręcznie)'
    'cfg.java.forceWs'    = 'Otwierać workspace w kontenerze FSLogix bez pytania (zalecane w laboratoriach studenckich)?'
    'cfg.java.heap'       = 'Maksymalna pamięć IDE -Xmx w MB (0 = domyślna JVM, ok. 1/4 RAM maszyny)'
    'cfg.java.heapBad'    = '{0} to nie 0 ani 512-32768 - przyjmuję 0 (domyślna JVM)'
    'cfg.java.caches'     = 'Wykluczyć cache Maven/Gradle (.m2\repository, .gradle\caches) z kontenera FSLogix? Tylko przy bliskim mirrorze Maven - pobierają się wtedy od nowa w każdej sesji'
    'cfg.java.noPkg'      = 'Pakietu {0} nie ma ani w manifeście, ani w szablonie - pomijam'
    'cfg.java.pkgAdded'   = 'Pakiet {0} dodany do manifestu z szablonu'
    'cfg.java.jeeDownload' = '-Mode Download pobiera tylko ZIP java: eclipse-jee-<RRRR-MM>-R-win32-x86_64.zip wrzuć do Apps\Eclipse samodzielnie'
    'cfg.java.done'       = 'Java: JDK {0}, Eclipse {1} | Arguments EclipseJava: {2}'

    'cfg.step3'           = 'Krok 4/8: FSLogix (kontenery profili)'
    'cfg.fsl.share'       = 'Udział na kontenery profili (UNC, np. \\fs01\Profiles$; Enter = pomiń)'
    'cfg.fsl.none'        = 'FSLogix: bez udziału - konfiguracja pozostaje wyłączona'
    'cfg.fsl.notUnc'      = 'To nie jest ścieżka UNC: {0} - pomijam'
    'cfg.fsl.size'        = 'Maksymalny rozmiar VHDX w MB'
    'cfg.fsl.include'     = 'Grupy z kontenerem, oddzielone przecinkami (Enter = wszyscy)'
    'cfg.fsl.exclude'     = 'Konta/grupy BEZ kontenera, np. DOMENA\VDI-Admins (Enter = brak)'
    'cfg.fsl.noPkg'       = 'Brak wpisu FSLogixConfig w manifeście - pomijam'
    'cfg.fsl.done'        = 'FSLogixConfig: {0} (włączony)'

    'cfg.step4'           = 'Krok 5/8: Horizon Agent i App Volumes'
    'cfg.hz.help'         = 'Funkcje Horizon Agent (ADDLOCAL): Core i NGVC (Instant Clone) są wymagane; Core zawiera już Blast, PCoIP i Media Optimization for Teams. Opcjonalne: USB, RTAV (kamera/mikrofon), ClientDriveRedirection, ScannerRedirection, SmartCard, SerialPortRedirection, GEOREDIR, PerfTracker, HelpDesk, PrintRedir.'
    'cfg.hz.features'     = 'Horizon Agent ADDLOCAL (po przecinku; Enter = propozycja dla profilu)'
    'cfg.av.manager'      = 'Adres App Volumes Manager (FQDN; Enter = bez zmian)'
    'cfg.av.port'         = 'Port App Volumes Manager'

    'cfg.step5'           = 'Krok 6/8: ustawienia regionalne budowy obrazu (OOBE po Generalize)'
    'cfg.bld.tz'          = 'Strefa czasowa (Get-TimeZone -ListAvailable)'
    'cfg.bld.system'      = 'Ustawienia regionalne systemu'
    'cfg.bld.user'        = 'Format daty/liczb użytkownika'
    'cfg.bld.input'       = 'Klawiatura'
    'cfg.bld.ui'          = 'Język interfejsu po OOBE = zainstalowany język Windows ({0})'

    'cfg.step6'           = 'Krok 7/8: OSOT - Teams, OneDrive, efekty wizualne'
    'cfg.osot.none'       = 'Brak sekcji Osot w manifeście - pomijam'
    'cfg.osot.notif'      = 'Zachować powiadomienia aplikacji (Teams: czat, połączenia przychodzące)?'
    'cfg.osot.onedrive'   = 'Użytkownicy trzymają dane w OneDrive (Known Folder Move) - zachować i zainstalować OneDrive dla całej maszyny?'
    'cfg.osot.noFile'     = 'Brak pliku wyborów OSOT {0} - pomijam'
    'cfg.osot.odPkg'      = 'Pakiet OneDrive (per-machine): {0}'
    'cfg.osot.odMissing'  = 'Brak wpisu OneDrive w manifeście - dodaj OneDriveSetup.exe do Apps\ (docs/pl/profiles-gpo.md)'
    'cfg.osot.changed'    = 'Optimize.json: zmieniono {0} pozycji (powiadomienia: {1}, OneDrive: {2}, efekty: {3})'
    'cfg.osot.same'       = 'Optimize.json: bez zmian'
    'cfg.osot.verify'     = 'Do sprawdzenia na klonie: czy "Let Windows apps run in the background" (Optimize.json) nie blokuje Teams w tle'

    'cfg.step7'           = 'Krok 8/8: aplikacje winget'
    'cfg.wg.noCatalog'    = 'Brak katalogu {0} - pomijam wybór aplikacji'
    'cfg.col.name'        = 'Nazwa'
    'cfg.col.category'    = 'Kategoria'
    'cfg.col.profile'     = 'Dla profilu'
    'cfg.col.suggest'     = 'Polecane'
    'cfg.col.current'     = 'Obecnie'
    'cfg.col.block'       = 'Blokada aktualizacji'
    'cfg.wg.current'      = 'Obecnie w manifeście: {0}'
    'cfg.wg.title'        = 'Zaznacz aplikacje do instalacji w obrazie (Ctrl/Shift = wiele), potem OK'
    'cfg.wg.nothing'      = 'Nic nie zaznaczono.'
    'cfg.wg.keep'         = 'zostaw obecną listę'
    'cfg.wg.suggested'    = 'użyj polecanych dla profilu ({0})'
    'cfg.wg.again'        = 'wybierz ponownie'
    'cfg.wg.none'         = 'bez aplikacji winget'
    'cfg.wg.selected'     = 'Wybrano ({0}): {1}'
    'cfg.wg.done'         = 'Winget.Install: {0} aplikacji'

    'cfg.save'            = 'Zapis manifestu'
    'cfg.done'            = 'Konfiguracja zapisana. Dalej: -Mode Download (darmowe pakiety), -Mode PackageList (plan), potem -Mode Update lub budowa: Optimize -> Generalize'
}
