@{
    'dl.step'           = 'DOWNLOAD - darmowe pakiety (Microsoft, VMware, Eclipse) prosto do C:\install'
    'dl.catalog'        = 'Katalog: {0}'
    'dl.indexEmpty'     = 'Brak pasującego pliku na liście {0}'
    'dl.from'           = 'Źródło: {0}'
    'dl.noSigCheck'     = '{0}: bez sprawdzania Authenticode (podpis MSIX sprawdza Windows przy instalacji)'
    'dl.badSig'         = '{0}: nieprawidłowy podpis ({1}, {2}) - plik odrzucony'
    'dl.current'        = '{0}: już aktualny'
    'dl.saved'          = '{0}: zapisano ({1} MB)'
    'dl.oldRemoved'     = 'Usunięto starszą wersję: {0}'
    'dl.notInZip'       = 'Nie znaleziono {0} w {1}'
    'dl.zipChecked'     = 'Podpisy {0} plików w archiwum są prawidłowe'
    'dl.failed'         = '[{0}] pobieranie nieudane: {1}'
    'dl.summary'        = 'Podsumowanie'
    'dl.counts'         = 'Nowe: {0}, już aktualne: {1}, nieudane: {2}'
    'dl.manual'         = 'Pobierz ręcznie (wymagane logowanie lub wybór wersji) - patrz docs/pl/downloads.md:'
    'dl.manual.osot'    = 'Omnissa Horizon OS Optimization Tool (OSOT) -> OSOT\'
    'dl.manual.agents'  = 'Omnissa Horizon Agent, Dynamic Environment Manager, App Volumes Agent (wersje zgodne z backendem) -> Horizon\'
    'dl.manual.patches' = 'Aktualizacje zbiorcze Windows (MSU) z Microsoft Update Catalog -> Patches\'
    'dl.manual.nvidia'  = 'Sterownik gościa NVIDIA vGPU i token licencji (tylko profil Grafik)'
    'dl.someFailed'     = 'Nieudane pobieranie: {0} - sprawdź ostrzeżenia powyżej'
    'dl.release'        = 'Bieżące wydanie: {0}'
    'dl.noRelease'      = 'Nie można odczytać bieżącego wydania z {0}'

    'osot.toolCopied'   = '{0} skopiowany do {1} (wymagany przez OSOT Finalize {2})'
    'osot.toolMissing'  = 'OSOT Finalize {0} wymaga {1} - nie znaleziono (uruchom -Mode Download)'
}
