@{
    # --- platforma pakietów ---
    'pkg.noInstallDir'   = 'Brak katalogu {0}'
    'pkg.createDefault'  = 'Brak manifestu {0} - tworzę domyślny (komponenty Horizon wyłączone, do uzupełnienia)'
    'pkg.jsonError'      = 'Błąd składni JSON w {0}: {1}'
    'pkg.unzip'          = 'Rozpakowuję {0}'
    'pkg.readHotfix'     = 'Odczyt zainstalowanych poprawek (Get-HotFix + Get-WindowsPackage)...'
    'pkg.noOdtXml'       = '[{0}] brak XML konfiguracji ODT obok {1}'
    'pkg.unknownType'    = '[{0}] nieznany typ ''{1}'''
    'pkg.okReboot'       = '[{0}] {1}: OK, wymagany restart (kod {2})'
    'pkg.ok'             = '[{0}] {1}: OK (kod {2})'
    'pkg.error'          = '[{0}] {1}: BŁĄD kod {2} (0x{3:X8}), log: {4}'
    'pkg.stepPlan'       = 'PAKIETY - plan instalacji (podgląd)'
    'pkg.stepInstall'    = 'PAKIETY - instalacja z manifestu'
    'pkg.manifest'       = 'Manifest: {0}'
    'pkg.nothing'        = 'Brak pakietów do instalacji'
    'pkg.needsReboot'    = '[{0}] wymaga restartu przed kolejnymi pakietami'
    'pkg.summary'        = 'Pakiety: zainstalowano {0}, błędy {1}'
    'pkg.allAssigned'    = 'Wszystkie paczki w {0} mają wpis w manifeście (lub są na liście Ignore)'
    'pkg.unassigned'     = 'Pliki w {0} BEZ wpisu w manifeście (nie będą instalowane) - uruchom -Mode Discover:'

    'plan.none'                  = '(brak)'
    'plan.noId'                  = '(bez Id)'
    'plan.byChannel'             = 'wg kanału'
    'plan.action.install'        = 'instaluj'
    'plan.action.update'         = 'aktualizuj'
    'plan.action.skip'           = 'pomiń'
    'plan.action.current'        = 'aktualny'
    'plan.action.missing'        = 'brak pliku'
    'plan.reason.requireInstalled' = 'nie jest zainstalowany (RequireInstalled)'
    'plan.reason.new'            = 'nowa instalacja'
    'plan.reason.noVersion'      = 'nie można odczytać wersji paczki (dodaj "Version" w manifeście)'
    'plan.reason.disabledTag'    = '(wyłączony)'
    'plan.reason.noOdtXml'       = 'brak XML konfiguracji ODT (<Add>) obok setup.exe ani pliku z pola Config'
    'plan.reason.always'         = 'uruchamiany zawsze'
    'plan.reason.disabled'       = 'wyłączony w manifeście (byłoby: {0})'
    'plan.reason.notSelected'    = 'poza -PackageIds (byłoby: {0})'

    # --- discover ---
    'disc.step'         = 'DISCOVER - manifest dopasowany do bieżącego obrazu i zawartości C:\install'
    'disc.complete'     = 'Brak nowych plików do opisania - manifest jest kompletny'
    'disc.x86'          = 'wariant x86 (obraz x64)'
    'disc.patchName'    = 'Poprawki {0} z {1}'
    'disc.rootDir'      = 'katalogu głównego'
    'disc.newOn'        = 'nowy wpis (włączony)'
    'disc.newOff'       = 'nowy wpis (wyłączony)'
    'disc.byKb'         = 'poprawki wg KB'
    'disc.skipped'      = 'pominięty'
    'disc.archive'      = 'archiwum/nieznany typ - opisz ręcznie (pole Archive)'
    'disc.exeNote'      = 'uzupełnij parametry cichej instalacji, potem ustaw Enabled=true'
    'disc.installed'    = 'zainstalowany: {0} {1}'
    'disc.notInstalled' = 'nie jest zainstalowany na obrazie'
    'disc.infra'        = 'komponent VDI - włącz świadomie'
    'disc.proposals'    = 'Propozycje'
    'disc.applied'      = 'Manifest zaktualizowany: {0}'
    'disc.saved'        = 'Propozycja zapisana: {0}'
    'disc.applyHint'    = 'Przejrzyj ją i zastosuj: -Mode Discover -Apply (kopia obecnego manifestu zostanie zachowana)'

    # --- init ---
    'init.step'           = 'INIT - struktura katalogu {0}'
    'init.patches'        = 'poprawki Windows *.msu / *.cab (wg KB) oraz poprawki aplikacji *.msp'
    'init.office'         = 'Office Deployment Tool: setup.exe + Configuration_x64.xml (pobrane pliki trafią do Office\Data)'
    'init.fslogix'        = 'FSLogix_*.zip, oficjalna paczka Microsoft'
    'init.horizon'        = 'VMware Tools, Horizon Agent, DEM, App Volumes Agent (wpisy w manifeście Enabled=false)'
    'init.osot'           = 'Omnissa OS Optimization Tool (*.exe) + Optimize.json (Export Selections), LGPO.exe, sdelete64.exe'
    'init.teams'          = 'teamsbootstrapper.exe + MSTeams-x64.msix'
    'init.apps'           = 'własne aplikacje MSI/EXE/MSIX'
    'init.scripts'        = 'skrypty konfiguracyjne PS1'
    'init.created'        = 'Utworzono {0}'
    'init.exists'         = 'Istnieje  {0}'
    'init.readmeTitle'    = 'Struktura {0} (VDI-ImageMaint)'
    'init.readmeStart'    = 'zacznij tutaj (menu)'
    'init.readmeScript'   = 'narzędzie'
    'init.readmeManifest' = 'manifest pakietów + konfiguracja OSOT (sekcja "Osot")'
    'init.readmeRecursive'= 'Pliki mogą leżeć w dowolnym podfolderze - wyszukiwanie jest rekurencyjne.'
    'init.readmeList'     = 'Pliki bez wpisu w manifeście pokazuje: .\VDI-ImageMaint.ps1 -Mode PackageList'
    'init.readme'         = 'Opis struktury: {0}'
    'init.noMove'         = 'Istniejących plików nie przenoszę - mogą zostać w obecnych miejscach.'
}
