@{
    'seal.step'            = 'SEAL - blokada automatycznych aktualizacji'
    'seal.baseline'        = 'Stan bazowy sprzed OSOT zapisany: {0}'
    'seal.policy'          = 'Polityka: {0}\{1} = {2}'
    'seal.svc.missing'     = 'Usługa {0} nie istnieje - pomijam'
    'seal.svc.disabled'    = 'Usługa {0}: Disabled (było Start={1})'
    'seal.svc.protected'   = 'Usługa {0}: brak uprawnień do zmiany (chroniona) - uruchom z -AsSystem'
    'seal.svc.stopFailed'  = 'Usługa {0}: nie udało się zatrzymać ({1})'
    'seal.task.disabled'   = 'Zadanie wyłączone: {0}'
    'seal.task.protected'  = 'Zadanie chronione, nie wyłączono: {0} (użyj -AsSystem)'
    'seal.type.Task'       = 'Zadanie'
    'seal.type.Service'    = 'Usługa'
    'seal.detect.none'     = 'Nie wykryto dodatkowych aktualizatorów'
    'seal.detect.reportOnly' = 'Wykryto (NIE zablokowano, -NoBlockDetected): [{0}] {1} -> {2}'
    'seal.detect.found'    = 'Wykryto: [{0}] {1} -> {2}'
    'seal.file.disabled'   = 'Aktualizator wyłączony: {0}'
    'seal.pendingReboot'   = 'Oczekuje restart ({0}). Zrestartuj VM przed Seal - inaczej oczekujące operacje wykonają się na każdym klonie. (-Force pomija sprawdzenie)'
    'seal.pendingWarn'     = 'Uwaga: oczekujący restart ({0})'
    'seal.already'         = 'Obraz był już zapieczętowany ({0}) - uzupełniam brakujące elementy'
    'seal.fromBaseline'    = 'Stan bazowy z {0} - kontynuuję Seal'
    'seal.sec.policies'    = 'Polityki'
    'seal.sec.services'    = 'Usługi'
    'seal.sec.tasks'       = 'Zadania harmonogramu'
    'seal.sec.files'       = 'Aktualizatory aplikacji'
    'seal.sec.detect'      = 'Wykrywanie innych mechanizmów aktualizacji'
    'seal.stateSaved'      = 'Zapis stanu: {0}'
    'seal.doneWarn'        = 'Seal zakończony z {0} ostrzeżeniami - uruchom ponownie z -AsSystem'
    'seal.done'            = 'Seal zakończony poprawnie'
    'seal.next'            = 'Dalej: wyłącz VM -> snapshot -> Horizon Console: Push Image (Instant Clone)'

    'cleanup.step'         = 'Czyszczenie obrazu'
    'cleanup.sd'           = 'SoftwareDistribution\Download wyczyszczony'
    'cleanup.do'           = 'Pamięć podręczna Delivery Optimization wyczyszczona'
    'cleanup.doSkipped'    = 'Pamięć podręczna Delivery Optimization - pominięto'
    'cleanup.temp'         = 'Katalogi TEMP wyczyszczone'
    'cleanup.dism'         = 'DISM /StartComponentCleanup (może potrwać kilka-kilkanaście minut)...'
    'cleanup.dismDone'     = 'DISM zakończony, kod: {0}'

    'unlock.step'          = 'UNLOCK - odblokowanie mechanizmów aktualizacji'
    'unlock.noState'       = 'Brak zapisu stanu Seal - przywracam tylko wartości ustawione przez to narzędzie'
    'unlock.policyRemoved' = 'Polityka usunięta: {0}'
    'unlock.svc'           = 'Usługa {0}: Start={1}'
    'unlock.svcDenied'     = 'Usługa {0}: brak uprawnień (-AsSystem)'
    'unlock.file'          = 'Przywrócono: {0}'
    'unlock.tasksUnknown'  = 'Zadania harmonogramu pozostawiono bez zmian (brak informacji o stanie pierwotnym)'
    'unlock.policy'        = 'Polityka przywrócona: {0}'
    'unlock.policyFailed'  = 'Polityka {0}: {1}'
    'unlock.task'          = 'Zadanie włączone: {0}'
    'unlock.taskDenied'    = 'Zadanie {0}: nie włączono (-AsSystem)'
    'unlock.done'          = 'Stan przywrócony w całości, zapis Seal usunięty'
    'unlock.partial'       = 'Przywrócono z {0} problemami - zapis stanu zachowany, uruchom Unlock z -AsSystem'
}
