@{
    'val.step'          = 'VALIDATE - manifest {0}'
    'val.noFile'        = 'Nie znaleziono manifestu {0} (uruchom -Mode Init albo -Mode Configure)'
    'val.json'          = 'Błąd składni JSON: {0}'
    'val.notString'     = 'musi być tekstem w cudzysłowie'
    'val.notBool'       = 'musi być true albo false bez cudzysłowu (teraz: {0}) - "false" w cudzysłowie oznacza prawdę'
    'val.notInt'        = 'musi być liczbą całkowitą bez cudzysłowu (teraz: {0})'
    'val.notObject'     = 'musi być obiektem JSON (w nawiasach klamrowych)'
    'val.notArray'      = 'musi być listą [ ... ]'
    'val.badRegex'      = 'nieprawidłowe wyrażenie regularne ''{0}'': {1}'
    'val.badEnum'       = 'wartość ''{0}'' jest niedozwolona - użyj jednej z: {1}'
    'val.unknownField'  = 'nieznane pole (literówka? narzędzie je pomija)'
    'val.didYouMean'    = '- czy chodziło o ''{0}''?'
    'val.finalizeStep'  = 'nieznany krok OSOT Finalize ''{0}'' (dozwolone: 0-11 albo all)'
    'val.finalizeCompact' = 'krok 2 (Compact) kosztuje CPU na każdym klonie Instant Clone - niezalecany'
    'val.finalizeZero'  = 'krok 7 (zerowanie wolnego miejsca) tylko przy pierwszej budowie przed eksportem do dysku thin, nie w cyklu Day-2'
    'val.teamsRemoved'  = '-storeapp remove-all bez --exclude MSTeams usuwa nowy Teams z obrazu'
    'val.missingFile'   = 'nie znaleziono pliku: {0}'
    'val.unknownId'     = 'w Packages nie ma pakietu o Id ''{0}'''
    'val.required'      = 'brak wymaganego pola {0}'
    'val.duplicateId'   = 'Id ''{0}'' występuje więcej niż raz'
    'val.detectNeeds'   = 'Detect typu {0} wymaga pola {1}'
    'val.unknownVar'    = 'nieznana zmienna {{{0}}} - zdefiniuj ją w Variables (wbudowane: File, Dir, Log, InstallDir)'
    'val.noPackageFile' = 'brak jeszcze pliku pasującego do ''{0}'' (skopiuj go albo uruchom -Mode Download)'
    'val.noShare'       = 'FSLogixConfig jest włączony, ale Variables.FSLogixShare jest puste'
    'val.summaryErr'    = 'Manifest: błędy {0}, ostrzeżenia {1} - popraw błędy przed instalacją'
    'val.summaryWarn'   = 'Manifest: bez błędów, ostrzeżenia {0}'
    'val.ok'            = 'Manifest jest poprawny'
    'val.failed'        = 'Manifest zawiera błędy (patrz wyżej)'
    'val.blocked'       = 'Instalacja zatrzymana: manifest zawiera błędy ({0}). Popraw je (-Mode Validate) i uruchom ponownie.'
    'val.hz.managed'    = 'Horizon Agent: wymagany VDM_VC_MANAGED_AGENT=1 (pulpit zarządzany przez vCenter, Instant Clone)'
    'val.hz.feature'    = 'Horizon Agent: nieznana opcja ADDLOCAL ''{0}'' (literówka albo usunięta, np. V4V od 2412)'
    'val.hz.core'       = 'Horizon Agent: ADDLOCAL z listą funkcji musi zawierać Core'
    'val.hz.ngvc'       = 'Horizon Agent: brak NGVC (Instant Clone Agent) w ADDLOCAL - obrazu nie da się użyć w pulach Instant Clone'
}
